= ग़ालिब के ख़तूत
दीपक जोइस <deepak.jois@gmail.com>

== मीर मेहदी मजरूह के नाम
अहा हा हा! मेरा प्यारा मीर मेहदी आया। आओ भाई मिज़ाज तो अच्छा है? बैठो, यह रामपुर है, दारुल-सुरूर है। जो लुत्फ़ यहाँ है, वह और कहाँ है? पानी, सुबहानल्लाह! शहर से तीन सौ क़दम पर एक दरिया है और कोसी उसका नाम है, बे शुब्हा चश्म-ए-आब-ए-हयात की कोई सोत इस में मिली है। ख़ैर, अगर यूँ भी है तो भाई, आब-ए-हयात उम्र बढ़ाता है, लेकिन इतना शीरीन कहाँ होगा।

तुम्हारा ख़त पहुँचा, तरद्दुद अबस। मेरा मकान डाक घर के क़रीब और डाक मुंशी मेरा दोस्त। न उर्फ़ लिखने की हाजत, न मोहल्ले की हाजत। बे विस्वास ख़त भेज दिया कीजिए और जवाब लिया कीजिए। यहाँ का हाल सब तरह खूब है और सोहबत मरग़ूब है। इस वक़्त तक मेहमान हूँ। देखूँ, क्या होता है। ताज़ीम-ओ-तौक़ीर में कोई दक़ीक़ा फ़रो-गुज़ाश्त नहीं है। लड़के दोनों मेरे साथ आये हैं। इस वक़्त इस से ज़्यादा नहीं लिख सकता।

– ग़ालिब +
फ़रवरी 1860

'''

== मुंशी हरगोपाल तफ़ता के नाम
क्यों मिरज़ा तफ़ता, तुम बेवफ़ा या मैं गुनहगार? यह भी तो मुझको मालूम नहीं कि तुम कहाँ हो? अभी एक साहब मेरी मुलाक़ात को आए थे। तक़रीबन तुम्हारा ज़िक्र दरमियान आया। वह कहने लगे कि वह कोल में हैं। अब मैं हैरान हूँ कि ख़त कोल भेझूँ या सिकन्दराबाद! अगर कोल भेझूँ तो मसकन का पता क्या लिखूँ? बहर हाल सिकन्दराबाद भेझता हूँ। खु़दा करे पहुँच जाए। तुम्हारा दीवान बत़रीक़-ए-पारसल मेरे पास आया। मैंने हरगारे को राजा अमीर सिंघ बहादुर के घर का पता बता कर वहाँ  भिझवा दिया। यक़ीन है कि पहुँच गया होगा। पाँच चार दिन से सुनता हूँ कि वह मथुरा और अकबराबाद की तरफ़ गए हैं। मुझ से मिल कर नहीं गए हैं। बहर हाल इस ख़त का जवाब जल्द लिखो और ज़रूर लिखो।

भाई तुम <?> आदमी हो। जहाँ जाया करो, मुझ को लिख भेजा करो कि मैं वहाँ जाता हूँ या जहाँ जाओ वहाँ से ख़त लिखो। तुम्हारे ख़त के न आने से मुझे तश्वीश रहती है। मेरी तशवीश तुम को क्यों पसन्द है।

– ग़ालिब +
<?> <?> <?> 27 मार्च 1859

'''
