= ग़ालिब के ख़तूत
दीपक जोइस <deepak.jois@gmail.com>; Serajahmad Ansari <serajahmadnsr70@gmail.com>

== मीर मेहदी मजरूह के नाम
अहा हा हा! मेरा प्यारा मीर मेहदी आया। आओ भाई मिज़ाज तो अच्छा है? बैठो, यह रामपुर है, दारुल-सुरूर है। जो लुत्फ़ यहाँ है, वह और कहाँ है? पानी, सुबहानल्लाह! शहर से तीन सौ क़दम पर एक दरिया है और कोसी उसका नाम है, बे शुब्हा चश्म-ए-आब-ए-हयात की कोई सोत इस में मिली है। ख़ैर, अगर यूँ भी है तो भाई, आब-ए-हयात उम्र बढ़ाता है, लेकिन इतना शीरीन कहाँ होगा।

तुम्हारा ख़त पहुँचा, तरद्दुद अबस। मेरा मकान डाक घर के क़रीब और डाक मुंशी मेरा दोस्त। न उर्फ़ लिखने की हाजत, न मोहल्ले की हाजत। बे विस्वास ख़त भेज दिया कीजिए और जवाब लिया कीजिए। यहाँ का हाल सब तरह खूब है और सोहबत मरग़ूब है। इस वक़्त तक मेहमान हूँ। देखूँ, क्या होता है। ताज़ीम-ओ-तौक़ीर में कोई दक़ीक़ा फ़रो-गुज़ाश्त नहीं है। लड़के दोनों मेरे साथ आये हैं। इस वक़्त इस से ज़्यादा नहीं लिख सकता।

– ग़ालिब +
फ़रवरी 1860

'''

== मुंशी हरगोपाल तफ़ता के नाम
क्यों मिर्ज़ा तफ़ता, तुम बेवफ़ा या मैं गुनहगार? यह भी तो मुझको मालूम नहीं कि तुम कहाँ हो? अभी एक साहब मेरी मुलाक़ात को आए थे। तक़रीबन तुम्हारा ज़िक्र दरमियान आया। वह कहने लगे कि वह कोल में हैं। अब मैं हैरान हूँ कि ख़त कोल भेजूँ या सिकन्दराबाद! अगर कोल भेजूँ तो मसकन का पता क्या लिखूँ? बहर हाल सिकन्दराबाद भेजता हूँ। ख़ुदा करे पहुँच जाए। तुम्हारा दीवान बतरीक़-ए-पारसल मेरे पास आया। मैंने हरकारे को राजा उम्मीद सिंह बहादुर के घर का पता बता कर वहाँ भिजवा दिया। यक़ीन है कि पहुँच गया होगा। पाँच चार दिन से सुनता हूँ कि वह मथुरा और अकबराबाद की तरफ़ गए हैं। मुझ से मिल कर नहीं गए हैं। बहर हाल इस ख़त का जवाब जल्द लिखो और ज़रूर लिखो।

भाई तुम सय्याह आदमी हो। जहाँ जाया करो, मुझको लि भेजा करो कि मैं वहाँ जाता हूँ या जहाँ जाओ वहाँ से ख़त लिखो। तुम्हारे ख़त के न आने से मुझे तशवीश रहती है। मेरी तशवीश तुम को क्यों पसन्द है?

– ग़ालिब +
मोहर्रेरह एक शम्बा 27 मार्च 1859

'''

== क़ुरबान अली बेग सालिक के नाम
मेरी जान किन अौहाम में गिरफ्तार है? जहाँ बाप को पीट चुका, अब चचा को भी रो। ख़ुदा तुझ को जीता रखे और तेरे खयालात-ओ-एहतमालात को सूरत वक़ूई दे। यहाँ ख़ुदा से भी तवक़्क़ो बाकी नहीं, मख़लूक़ का क्या ज़िक्र? कुछ बन नहीं आती। अपना आप तमाशायी बन गया हूँ। रंज-ओ-ज़िल्लत से ख़ुश होता हूँ। यानी मैंने अपने को अपना ग़ैर तसव्वुर किया है। जो दुख मुझे पहुँचता है, कहता हूँ: लो ग़ालिब के एक और जूती लगी। बहुत इतराता था कि मैं बड़ा शायर और फ़ारसीदाँ हूँ। आज दूर-दूर तक मेरा जवाब नहीं। ले अब कर्ज़दारों को जवाब दे। सच तो यूँ है, ग़ालिब क्या मरा, बड़ा मुलहिद मरा, बड़ा काफ़िर मरा। हमने अज़ राहे ताज़ीम, जैसा बादशाहों को बाद उन के “जन्नत आरामगाह” व “अर्श नशमीन” ख़िताब देते हैं, चूँकि यह अपने को शाहे क़लम रवे सुख़न जानता था, “सक़र मक़र” और “हाविया ज़ाविया” ख़िताब तजवीज़ कर रखा है। “आइए नजमुद्दौला बहादुर!” एक कर्ज़दार का गरेबान में हाथ एक कर्ज़दार भी भोग सुना रहा है। मैं उन से पूछ रहा हूँ: “अजी हसरत नवाब साहब! नवाब साहब कैसे, औगलान साहब! आप सलजूक़ी और अफ़रासयाबी हैं। ये क्या बेहुरमती हो रही है? कुछ तो उकसो, कुछ तो बोलो।” बोले क्या बेहया,बेग़ैरत, कोठी से शराब, गनद्धी से ग़ुलाब, बज़ाज़ से कपड़ा, मेवा फ़रोश से आम, सर्राफ़ से दाम कर्ज़ लिए जाता था। ये भी सोचा होता, कहां से दूंगा।

== मिर्ज़ा अलाउद्दीन अहमद ख़ान अलायी के नाम

ख़ान ग़ालिब,
याद आता है कि तुम्हारे <?> से सुना था कि लुगात “दसातीर” की करहनग वहाँ है। अगर होती तो क्यों न भेज देते? ख़ैर। <?>

<?> <?> दरकार <?> अकसर <?> <?> तुम समर नोरस हो उस नहाल के जिस ने मेरी आँखों के सामने नशू-ओ-नमा पायी है और मैं हवा <?> यह नशी उस नहाल का रहा हूँ। क्यों कर तुम मुझको <?> न होगे। रही दीर वादीर, उस की <?> है : तुम दिल्ली आओ या मैं लोहारू आऊँ। तुम मजबूर, मैं <?>। ख़ुद कहता हूँ कि मेरा <?> ज़िनहार <?> न हो, जब तक न समझ लो कि मैं कौन हूँ और माजरा क्या है। दिनो, आलम दो हैं: एक आलम अरवाह और एक आलम आब-ओ-गिल।

हाकिम उन दोनों आलमों का वह एक है। जो जोद फरमाता है: “<?>” और फिर आप वगिल के मजरम आलम अरवाह में पाते हैं, लेकिन यूँ भी हवा है कि आलम अरवाह के गुनहगार को दुनिया में भेज <?> हो। <?> मैं <?> रजब 1212 <?> में रोबकारी के वास्ते यहाँ भेजा गया। तेरह बरस हवालात में रहा। 7 रजब 1225 <?> को मेरे वास्ते हुक्म दवाम जिस सादर हुआ। एक बेड़ी मेरे पावों में डाल दी और दिल्ली शहर की <?> <?> किया और मुझे ज़नदाल में डाल दिया। फ़कर नज़म-ओ-नसर को मशक्कत ठहराए। बरसों के याद में जेल ख़ाने से <?> तीन बरस <?> फिरता रहा। जब देखा कि यह कैदी गेरज पा है, दो हथकडियाँ और बढ़ा दीं। पाँव बेडी से फ़गार हाथ हथकडियों से ज़ख्मदार। मशक्कत मकररी और मुशकिल हो गयी। ताक़त इक क़लम जायल हो गयी। बेहया हूँ। साल गज़ से बेड़ी को <?> <?> <?>, हथकड़ियों के भाग। मेरठ, मोरादाबाद हो आया और पहुँचा। कुछ दिन कम दो महीने वहाँ रहा था कि फ़िर पकड़ा आया। अब अहद किया कि और न भागूंगा। भागूंगा क्या? भागने की ताक़त भी तो नहीं रही। हुक्म-ए-रिहाई देखिए कब सादर है। एक <?> सा अहतमाल है कि इसी माह <?> 1277 <?>  में छूट जाऊँ। बहर तक़रीर बाद रिहाई के तो आदमी सो आए अपने घर के और कहीं नहीं जाता। मैं भी बाद नजात सीधा आलम अरवाह को चला जाऊँगा।

– ग़ालिब
जनवरी 1860
