= ग़ालिब के ख़तूत
दीपक जोइस <deepak.jois@gmail.com>; सिराजअहमद अन्सारी <serajahmadnsr70@gmail.com>

== मीर मेहदी मजरूह के नाम
अहा हा हा! मेरा प्यारा मीर मेहदी आया। आओ भाई मिज़ाज तो अच्छा है? बैठो, यह रामपुर है, दारुल-सुरूर है। जो लुत्फ़ यहाँ है, वह और कहाँ है? पानी, सुबहानल्लाह! शहर से तीन सौ क़दम पर एक दरिया है और कोसी उसका नाम है, बे शुब्हा चश्म-ए-आब-ए-हयात की कोई सोत इस में मिली है। ख़ैर, अगर यूँ भी है तो भाई, आब-ए-हयात उम्र बढ़ाता है, लेकिन इतना शीरीन कहाँ होगा।

तुम्हारा ख़त पहुँचा, तरद्दुद अबस। मेरा मकान डाक घर के क़रीब और डाक मुंशी मेरा दोस्त। न उर्फ़ लिखने की हाजत, न मोहल्ले की हाजत। बे विस्वास ख़त भेज दिया कीजिए और जवाब लिया कीजिए। यहाँ का हाल सब तरह खूब है और सोहबत मरग़ूब है। इस वक़्त तक मेहमान हूँ। देखूँ, क्या होता है। ताज़ीम-ओ-तौक़ीर में कोई दक़ीक़ा फ़रो-गुज़ाश्त नहीं है। लड़के दोनों मेरे साथ आये हैं। इस वक़्त इस से ज़्यादा नहीं लिख सकता।

– ग़ालिब +
फ़रवरी 1860

'''

== मुंशी हरगोपाल तफ़ता के नाम
क्यों मिर्ज़ा तफ़ता, तुम बेवफ़ा या मैं गुनहगार? यह भी तो मुझको मालूम नहीं कि तुम कहाँ हो? अभी एक साहब मेरी मुलाक़ात को आए थे। तक़रीबन तुम्हारा ज़िक्र दरमियान आया। वह कहने लगे कि वह कोल में हैं। अब मैं हैरान हूँ कि ख़त कोल भेजूँ या सिकन्दराबाद! अगर कोल भेजूँ तो मसकन का पता क्या लिखूँ? बहर हाल सिकन्दराबाद भेजता हूँ। ख़ुदा करे पहुँच जाए। तुम्हारा दीवान बतरीक़-ए-पारसल मेरे पास आया। मैंने हरकारे को राजा उम्मीद सिंह बहादुर के घर का पता बता कर वहाँ भिजवा दिया। यक़ीन है कि पहुँच गया होगा। पाँच चार दिन से सुनता हूँ कि वह मथुरा और अकबराबाद की तरफ़ गए हैं। मुझ से मिल कर नहीं गए हैं। बहर हाल इस ख़त का जवाब जल्द लिखो और ज़रूर लिखो।

भाई तुम सय्याह आदमी हो। जहाँ जाया करो, मुझको लि भेजा करो कि मैं वहाँ जाता हूँ या जहाँ जाओ वहाँ से ख़त लिखो। तुम्हारे ख़त के न आने से मुझे तशवीश रहती है। मेरी तशवीश तुम को क्यों पसन्द है?

– ग़ालिब +
मोहर्रेरह एक शम्बा 27 मार्च 1859

'''

== क़ुरबान अली बेग सालिक के नाम
मेरी जान किन अौहाम में गिरफ्तार है? जहाँ बाप को पीट चुका, अब चचा को भी रो। ख़ुदा तुझ को जीता रखे और तेरे खयालात-ओ-एहतमालात को सूरत वक़ूई दे। यहाँ ख़ुदा से भी तवक़्क़ो बाकी नहीं, मख़लूक़ का क्या ज़िक्र? कुछ बन नहीं आती। अपना आप तमाशायी बन गया हूँ। रंज-ओ-ज़िल्लत से ख़ुश होता हूँ। यानी मैंने अपने को अपना ग़ैर तसव्वुर किया है। जो दुख मुझे पहुँचता है, कहता हूँ: लो ग़ालिब के एक और जूती लगी। बहुत इतराता था कि मैं बड़ा शायर और फ़ारसीदाँ हूँ। आज दूर-दूर तक मेरा जवाब नहीं। ले अब कर्ज़दारों को जवाब दे। सच तो यूँ है, ग़ालिब क्या मरा, बड़ा मुलहिद मरा, बड़ा काफ़िर मरा। हमने अज़ राहे ताज़ीम, जैसा बादशाहों को बाद उन के “जन्नत आरामगाह” व “अर्श नशमीन” ख़िताब देते हैं, चूँकि यह अपने को शाहे क़लम रवे सुख़न जानता था, “सक़र मक़र” और “हाविया ज़ाविया” ख़िताब तजवीज़ कर रखा है। “आइए नजमुद्दौला बहादुर!” एक कर्ज़दार का गरेबान में हाथ एक कर्ज़दार भी भोग सुना रहा है। मैं उन से पूछ रहा हूँ: “अजी हसरत नवाब साहब! नवाब साहब कैसे, औगलान साहब! आप सलजूक़ी और अफ़रासयाबी हैं। ये क्या बेहुरमती हो रही है? कुछ तो उकसो, कुछ तो बोलो।” बोले क्या बेहया,बेग़ैरत, कोठी से शराब, गनद्धी से ग़ुलाब, बज़ाज़ से कपड़ा, मेवा फ़रोश से आम, सर्राफ़ से दाम कर्ज़ लिए जाता था। ये भी सोचा होता, कहां से दूंगा।

– ग़ालिब

'''

== मिर्ज़ा अलाउद्दीन अहमद ख़ान अलायी के नाम

जाने ग़ालिब!
याद आता है कि तुम्हारे ग़म-ए-नामदार से सुना था कि लुग़ात “दसातीर” की फ़रहंग वहाँ है। अगर होती तो क्यों न भेज देते? ख़ैर।

_आंचेह मा दरकार दारेम अकसरे दरकार नीस्त।_

 तुम समर-ए-नौरस हो उस नेहाल के जिस ने मेरी आँखों के सामने नशो नुमा पायी है और मैं हवा ख़्वाह व साया नशीं इस नेहाल का रहा हूँ। क्यों कर तुम मुझको अज़ीज़ न होगे? रही दीद व दीद, इस की दो सूरतें हैं : तुम दिल्ली आओ या मैं लोहारू आऊँ। तुम मजबूर, मैं माज़ूर। ख़ुद कहता हूँ कि मेरा उज़्र ज़िनहार मस्मूअ न हो, जब तक न समझ लो कि मैं कौन हूँ और माजरा क्या है। 

सुनो, आलम दो हैं: एक आलम-ए-अरवाह और एक आलम-ए-आब-ओ-गिल। हाकिम इन दोनों आलमों का वह एक है, जो ख़ुद फरमाता है: “लेमनिल मुल्कुल यौम?” और फिर आप जवाब देता है: “लिल्लाहिल वाहिदिल क़ह्हार”। हर चंद क़ाएदा-ए-आम यह है कि आलम-ए-आब-ओ-गिल वगिल के मुजरिम आलम-ए-अरवाह में सज़ा पाते हैं, लेकिन यूँ भी हुआ है कि आलम-ए-अरवाह के गुनहगार को दुनिया में भेज कर सज़ा देते हैं। चुनांचेह मैं आठवीं रज्जब सन् 1212 हि. में रोबकारी के वास्ते यहाँ भेजा गया। तेरह बरस हवालात में रहा। 7 रज्जब सन 1225 हि. को मेरे वास्ते हुक्म-ए-दवाम जलस सादिर हुआ। एक बेड़ी मेरे पावों में डाल दी और दिल्ली शहर को ज़िन्दाँ मुक़र्रर किया और मुझे उस ज़िन्दाँ में डाल दिया। फ़िक्र-ए-नज़म-ओ-नसर को मशक्कत ठहराया। बरसों के बाद में जेल ख़ाना से भागा। तीन बरस बलाद-ए-शरक़ियह में फिरता रहा। पायानकार  मुझे कलकत्ता से पकड़ लाए, फिर उसी मजलस में बिठा दिया। जब देखा कि यह कैदी गुरेज़पा है, दो हथकडियाँ और बढ़ा दीं। पाँव बेड़ी से फ़गार, हाथ हथकडियों से ज़ख्मदार। मशक्कत मुकर्ररी और मुशकिल हो गयी। ताक़त यक क़लम ज़ायल हो गयी। बे हया हूँ। साल-ए-गुज़िशता बेड़ी को ज़ाविया-ए-ज़िन्दाँ में छोड़, मअ दोनों हथकड़ियों के भागा। मेरठ, मोरादाबाद होता हुआ रामपुर पहुँचा। कुछ दिन कम दो महीने वहाँ रहा था कि फिर पकड़ा आया। अब अहद किया कि और न भागूंगा। भागूंगा क्या? भागने की ताक़त भी तो न रही। हुक्म-ए-रिहाई देखिए कब सादिर हो। एक ज़ईफ़ सा एहतमाल है कि इसी माह ज़िल हिज्जा 1277 हि. में छूट जाऊँ। बहर तक़दीर बाद रिहाई के तो आदमी सिवाए अपने घर के और कहीं नहीं जाता। मैं भी बाद-ए-निजात सीधा आलम-ए-अरवाह को चला जाऊँगा।

– ग़ालिब +
यकम जनवरी 1860

== चौधरी अबदुल ग़फ़ूर ‘सुरूर’ के नाम

जनाब चौधरी साहब आपका इनायतनामा उस वक़त पहुँचा और यह वक़्त सज का है दिन <?> का <?> की चौबीसवीं और <?> की पहली किताब के पारसल की रसीद मालूम हुई हकीम अबदुल रहम खाँ कोई नामी और नामावर आदमी नहीँ हैं। यहाँ के क़ाज़ी ज़ादों में से एक शख़्स हैं बत बाबत कहने लगे हैं मेरे भी आशना हैं। मगर सिर्फ़ सलाम आलिक ज़्यादा रबत नहीं है सवाल <?> हल मुझको कुछ मालूम नहीं कि वह कहाँ में और किस तरह हैं। आगे हज़रत साहब की ख़िदमत में अर्ज़ किया था कि आप जो कुछ लिखें वह <?> चौधरी साहब लिखा जाए। हज़रत ने न माना और फिर इबादत <?> लिखी <?> न मुझसे न और किसी से पढ़ी <?> न चार आप का ख़त फिर आपको भेजता हूँ। हज़रत से कुछ मत फ़रमाइएगा मगर उस इबादत को आपने हाथ नकल कर के मुझको भिजवाइएगा ज़रूर और जल्द। शफ़ीक़ मकद मरख़बाब चौधरी साहब ग़ुलाम रसूल कि ख़िदमत में सलाम पहुँचे।
