= ग़ालिब के ख़तूत
दीपक जोइस <deepak.jois@gmail.com>; सेराज अहमद अन्सारी <serajahmadnsr70@gmail.com>; सुरभि अगरवाल <surabhiagwl@gmail.com>

== मीर मेहदी मजरूह के नाम
अहा हा हा! मेरा प्यारा मीर मेहदी आया। आओ भाई मिज़ाज तो अच्छा है? बैठो, यह रामपुर है, दारुल-सुरूर है। जो लुत्फ़ यहाँ है, वह और कहाँ है? पानी, सुबहानल्लाह! शहर से तीन सौ क़दम पर एक दरिया है और कोसी उसका नाम है, बे शुब्हा चश्म-ए-आब-ए-हयात की कोई सोत इस में मिली है। ख़ैर, अगर यूँ भी है तो भाई, आब-ए-हयात उम्र बढ़ाता है, लेकिन इतना शीरीन कहाँ होगा।

तुम्हारा ख़त पहुँचा, तरद्दुद अबस। मेरा मकान डाक घर के क़रीब और डाक मुंशी मेरा दोस्त। न उर्फ़ लिखने की हाजत, न मोहल्ले की हाजत। बे विस्वास ख़त भेज दिया कीजिए और जवाब लिया कीजिए। यहाँ का हाल सब तरह खूब है और सोहबत मरग़ूब है। इस वक़्त तक मेहमान हूँ। देखूँ, क्या होता है। ताज़ीम-ओ-तौक़ीर में कोई दक़ीक़ा फ़रो-गुज़ाश्त नहीं है। लड़के दोनों मेरे साथ आये हैं। इस वक़्त इस से ज़्यादा नहीं लिख सकता।

– ग़ालिब +
फ़रवरी 1860

'''

== मुंशी हरगोपाल तफ़ता के नाम
क्यों मिर्ज़ा तफ़ता, तुम बेवफ़ा या मैं गुनहगार? यह भी तो मुझको मालूम नहीं कि तुम कहाँ हो? अभी एक साहब मेरी मुलाक़ात को आए थे। तक़रीबन तुम्हारा ज़िक्र दरमियान आया। वह कहने लगे कि वह कोल में हैं। अब मैं हैरान हूँ कि ख़त कोल भेजूँ या सिकन्दराबाद! अगर कोल भेजूँ तो मसकन का पता क्या लिखूँ? बहर हाल सिकन्दराबाद भेजता हूँ। ख़ुदा करे पहुँच जाए। तुम्हारा दीवान बतरीक़-ए-पारसल मेरे पास आया। मैंने हरकारे को राजा उम्मीद सिंह बहादुर के घर का पता बता कर वहाँ भिजवा दिया। यक़ीन है कि पहुँच गया होगा। पाँच चार दिन से सुनता हूँ कि वह मथुरा और अकबराबाद की तरफ़ गए हैं। मुझ से मिल कर नहीं गए हैं। बहर हाल इस ख़त का जवाब जल्द लिखो और ज़रूर लिखो।

भाई तुम सय्याह आदमी हो। जहाँ जाया करो, मुझको लि भेजा करो कि मैं वहाँ जाता हूँ या जहाँ जाओ वहाँ से ख़त लिखो। तुम्हारे ख़त के न आने से मुझे तशवीश रहती है। मेरी तशवीश तुम को क्यों पसन्द है?

– ग़ालिब +
मोहर्रेरह एक शम्बा 27 मार्च 1859

'''

== क़ुरबान अली बेग सालिक के नाम
मेरी जान किन अौहाम में गिरफ्तार है? जहाँ बाप को पीट चुका, अब चचा को भी रो। ख़ुदा तुझ को जीता रखे और तेरे खयालात-ओ-एहतमालात को सूरत वक़ूई दे। यहाँ ख़ुदा से भी तवक़्क़ो बाकी नहीं, मख़लूक़ का क्या ज़िक्र? कुछ बन नहीं आती। अपना आप तमाशायी बन गया हूँ। रंज-ओ-ज़िल्लत से ख़ुश होता हूँ। यानी मैंने अपने को अपना ग़ैर तसव्वुर किया है। जो दुख मुझे पहुँचता है, कहता हूँ: लो ग़ालिब के एक और जूती लगी। बहुत इतराता था कि मैं बड़ा शायर और फ़ारसीदाँ हूँ। आज दूर-दूर तक मेरा जवाब नहीं। ले अब कर्ज़दारों को जवाब दे। सच तो यूँ है, ग़ालिब क्या मरा, बड़ा मुलहिद मरा, बड़ा काफ़िर मरा। हमने अज़ राहे ताज़ीम, जैसा बादशाहों को बाद उन के “जन्नत आरामगाह” व “अर्श नशमीन” ख़िताब देते हैं, चूँकि यह अपने को शाहे क़लम रवे सुख़न जानता था, “सक़र मक़र” और “हाविया ज़ाविया” ख़िताब तजवीज़ कर रखा है। “आइए नजमुद्दौला बहादुर!” एक कर्ज़दार का गरेबान में हाथ एक कर्ज़दार भी भोग सुना रहा है। मैं उन से पूछ रहा हूँ: “अजी हसरत नवाब साहब! नवाब साहब कैसे, औगलान साहब! आप सलजूक़ी और अफ़रासयाबी हैं। ये क्या बेहुरमती हो रही है? कुछ तो उकसो, कुछ तो बोलो।” बोले क्या बेहया,बेग़ैरत, कोठी से शराब, गनद्धी से ग़ुलाब, बज़ाज़ से कपड़ा, मेवा फ़रोश से आम, सर्राफ़ से दाम कर्ज़ लिए जाता था। ये भी सोचा होता, कहां से दूंगा।

– ग़ालिब

'''

== मिर्ज़ा अलाउद्दीन अहमद ख़ान अलायी के नाम

जाने ग़ालिब!
याद आता है कि तुम्हारे ग़म-ए-नामदार से सुना था कि लुग़ात “दसातीर” की फ़रहंग वहाँ है। अगर होती तो क्यों न भेज देते? ख़ैर।

_आंचेह मा दरकार दारेम अकसरे दरकार नीस्त।_

 तुम समर-ए-नौरस हो उस नेहाल के जिस ने मेरी आँखों के सामने नशो नुमा पायी है और मैं हवा ख़्वाह व साया नशीं इस नेहाल का रहा हूँ। क्यों कर तुम मुझको अज़ीज़ न होगे? रही दीद व दीद, इस की दो सूरतें हैं : तुम दिल्ली आओ या मैं लोहारू आऊँ। तुम मजबूर, मैं माज़ूर। ख़ुद कहता हूँ कि मेरा उज़्र ज़िनहार मस्मूअ न हो, जब तक न समझ लो कि मैं कौन हूँ और माजरा क्या है। 

सुनो, आलम दो हैं: एक आलम-ए-अरवाह और एक आलम-ए-आब-ओ-गिल। हाकिम इन दोनों आलमों का वह एक है, जो ख़ुद फरमाता है: “लेमनिल मुल्कुल यौम?” और फिर आप जवाब देता है: “लिल्लाहिल वाहिदिल क़ह्हार”। हर चंद क़ाएदा-ए-आम यह है कि आलम-ए-आब-ओ-गिल वगिल के मुजरिम आलम-ए-अरवाह में सज़ा पाते हैं, लेकिन यूँ भी हुआ है कि आलम-ए-अरवाह के गुनहगार को दुनिया में भेज कर सज़ा देते हैं। चुनांचेह मैं आठवीं रज्जब सन् 1212 हि. में रोबकारी के वास्ते यहाँ भेजा गया। तेरह बरस हवालात में रहा। 7 रज्जब सन 1225 हि. को मेरे वास्ते हुक्म-ए-दवाम जलस सादिर हुआ। एक बेड़ी मेरे पावों में डाल दी और दिल्ली शहर को ज़िन्दाँ मुक़र्रर किया और मुझे उस ज़िन्दाँ में डाल दिया। फ़िक्र-ए-नज़म-ओ-नसर को मशक्कत ठहराया। बरसों के बाद में जेल ख़ाना से भागा। तीन बरस बलाद-ए-शरक़ियह में फिरता रहा। पायानकार  मुझे कलकत्ता से पकड़ लाए, फिर उसी मजलस में बिठा दिया। जब देखा कि यह कैदी गुरेज़पा है, दो हथकडियाँ और बढ़ा दीं। पाँव बेड़ी से फ़गार, हाथ हथकडियों से ज़ख्मदार। मशक्कत मुकर्ररी और मुशकिल हो गयी। ताक़त यक क़लम ज़ायल हो गयी। बे हया हूँ। साल-ए-गुज़िशता बेड़ी को ज़ाविया-ए-ज़िन्दाँ में छोड़, मअ दोनों हथकड़ियों के भागा। मेरठ, मोरादाबाद होता हुआ रामपुर पहुँचा। कुछ दिन कम दो महीने वहाँ रहा था कि फिर पकड़ा आया। अब अहद किया कि और न भागूंगा। भागूंगा क्या? भागने की ताक़त भी तो न रही। हुक्म-ए-रिहाई देखिए कब सादिर हो। एक ज़ईफ़ सा एहतमाल है कि इसी माह ज़िल हिज्जा 1277 हि. में छूट जाऊँ। बहर तक़दीर बाद रिहाई के तो आदमी सिवाए अपने घर के और कहीं नहीं जाता। मैं भी बाद-ए-निजात सीधा आलम-ए-अरवाह को चला जाऊँगा।

– ग़ालिब +
यकम जनवरी 1860

'''

== चौधरी अबदुल ग़फ़ूर ‘सुरूर’ के नाम

जनाब चौधरी साहब आपका इनायतनामा उस वक़त पहुँचा और यह वक़्त सुबह का है दिन बुध का रबीउल-सानी की चौबीसवीं और दिसम्बर की पहली किताब के पारसल की रसीद मालूम हुई हकीम अबदुल रहीम खाँ कोई नामी और नामावर आदमी नहीं हैं यहाँ के क़ाज़ीज़ादों में से एक शख़्स हैं अब तबाबत करने लगे हैं मेरे भी आशना हैं मगर सिर्फ़ सलाम अलैक ज़्यादा रब्त नहीं है सो उनका हाल मुझको कुछ मालूम नहीं कि वह कहाँ हैं और किस तरह हैं आगे हज़रत साहब की ख़िदमत में अर्ज़ किया था कि आप जो कुछ लिखें वह बक़लम चौधरी साहब लिखा जाए हज़रत ने न माना और फिर इबारत बदस्तख़त ख़ास लिखी वल्लाह बिल्लाह न मुझसे न और किसी से पढ़ी गई नाचार आप का ख़त फिर आपको भेजता हूँ हज़रत से कुछ न फ़रमाइएगा मगर उस इबारत को आपने हाथ से नक़ल कर के मुझको भिजवाइएगा ज़रूर और जल्द शफ़ीक़ मुकर्रम जनाब चौधरी साहब ग़ुलाम रसूल की ख़िदमत में सलाम पहुँचे।

– ग़ालिब

'''

== चौधरी अबदुल ग़फ़ूर ‘सुरूर’ के नाम

जनाब चौधरी साहब आप के तलत्तुफ़नामा के वरूद की मोसर्रत और पारसल के न पहुँचने की हैरत बाअस इस की हुई कि आप को फिर तकलीफ़ दूँ और बा अांकेह ख़त जवाब तलब न था जवाब लिखूँ बन्दा परवर मैंने पारसल की रसीद ले ली थी आप के ख़त को पढ़ कर कार पुरदाज़ान डाक के पास वह रसीद भिजवाई उन्होंने किताब देखकर मेरे आदमी से कह दिया कि सिकंदर रहराव की रसीद यह मौजूद है अब उस पारसल की जवाबदही वहाँ वालों के ज़िम्मा है यह सुन कर मैंने यूँ मुनासिब जाना कि वह रसीद आप के पास भेज दूँ आप सिकंदर रहराव के डाक ख़ाना मे भिजवा कर उनसे पारसल मंगवा लें और अब इस रसीद का मेरी तरफ़ राजे होना किसी सूरत में ज़रूर नहीं वस्सलाम।

– ग़ालिब

'''

=== मुंशी हरगोपाल तफ़्ता के नाम

साहिब!

दोनों ज़बानों से मुरक्किब है यह फ़ारसी मुतारफ़ : एक फ़ारसी, एक अरबी। हर चन्द इस मन्तिक़ में लुग़ात-ए-तुर्की भी आ जाते हैं मगर कमतर। मैं अरबी का आलिम नहीं, मगर निरा जाहिल भी नहीं। बस इतनी बात है कि इस ज़बान के लुग़ात का मुहक़्क़िक़ नहीं हूँ। उलमा से पूछने का मुहताज और सनद का तलबगार रहता हूँ। फ़ारसी में मब्दा-ए-फ़ैयाज़ से मुझे वह दस्तगाह मिली है और इस ज़बान के क़वाइद-ओ-ज़वाबित मेरे ज़मीर में इस तरह जागज़ीं हैं जैसे फ़ौलाद में जौहर।

अहल-ए-पारस में और मुझमें दो तरह के तफ़ावुत हैं: एक तो यह कि उनका मौलिद ईरान और मेरा मौलिद हिन्दुस्तान, दूसरे यह कि वह लोग आगे पीछे, सौ दो सौ, चार सौ, आठ सौ बरस पहले पैदा हुए हैं।

क्या हँसी आती है कि तुम मानन्द और शायरों के मुझको भी समझे हो कि उस्ताद की ग़ज़ल या क़सीदा सामने रख लिया, उसके क़वाफ़ी लिख लिये और इन क़ाफ़ियों पर लफ़्ज़ जोड़ने लगे। ला हौल व ला क़ुव्वत इला बिल्लाह। बचपन में जब मैं रेख़्ता लिखने लगा हूँ, लानत है मुझपर अगर मैंने कोई रेख़्ता या उसके क़वाफ़ी पेश-ए-नज़र रख लिये हों। सिर्फ़ बह्र और रदीफ़, क़ाफ़िया देख लिया और उस ज़मीन में ग़ज़ल, क़सीदा लिखने लगा। तुम कहते हो नज़ीरी का दीवान वक़्त-ए-तहरीर-ए-क़सीदा पेश-ए-नज़र होगा और जो इस क़ाफ़िये का शेर देखा इसपर लिखा होगा। वल्लाह अगर तुम्हारे इस ख़त के देखने से पहले मैं यह भी जानता हूँ कि इस ज़मीन में नज़ीरी का क़सीदा भी है। चे जा-ए-आंकि वह शेर। भाई शायरी माने आफ़रीन है, क़ाफ़िया पैमायी नहीं है।

“ज़मान” लफ़्ज़-ए-अरबी “अज़मिना” जमा, दोनों तरह फ़ारसी में मुस्तामल है। “ज़माने”, “यक ज़मान”, “हर ज़मान”, “ज़माँ ज़माँ”, “दर ईन ज़मान”, “दर आन ज़मान” सब सही और फ़सीह। जो इसको ग़लत कहे, वह गधा। बल्कि अहल-ए-फ़ार्स ने मिस्ल-ए-“मौज” ओ “मौजा” यहाँ भी “ہ” (“आ”) बढ़ाकर “ज़माना” इस्तेमाल किया है। “यक ज़मान” को मैंने कभी ग़लत न कहा

== मीर मेहदी के नाम

जान-ए-ग़ालिब अबकी की ऐसा बिमार हो गया था कि मुझको ख़ुद अफ़सोस था पांचवें दिन ग़िज़ा खाई अब अच्छा हूँ तनदुरुस्त हूँ ज़िल हिज्जा 1276 हि. तक कुछ खटका नहीं है मोहर्रम की पहली तारीख़ से अल्लाह मालिक है मीर नसीरुद्दीन आए कई बार मैंने उनको देखा नहीं अबकी बार दर्द में मुझको ग़फ़लत बहुत रही अकसर अहबाब के आने की ख़बर नहीं हुई जबसे अच्छा हुआ हूँ सय्यद साहब नहीं आए तुम्हारे आँखों के ग़ुबार की वजह यह है कि जो मकान दिल्ली में ढाए गए और जहाँ जहाँ सडकें निकलीं जितनी गर्द उडी उस को आपने अज़ राहे मुहब्बत अपनी आँखों में जगह दी बहर हाल अच्छे हो जाओ और जल्द आओ मुज्तहेदुलअस्र मीर सरफ़राज़ हुसैन का ख़त आया था मैंने मीरन साहब की आज़ुरदगी के ख़ौफ़ से उसका जवाब नहीं लिखा यह रुक़्आ उन दोनों साहबों को पढ़ा देना कि मीर सरफ़राज़ हुसैन साहब अपने ख़त की रसीद से मुत्तला हो जाएँ और मीरन साहब मेरे पास उलफ़त पर एत्तला पाएँ

– ग़ालिब

'''

== चौधरी अब्दुर ग़फ़ुर सुरूर के नाम

शफ़ीक मेरे इनायत फ़रमा मेरे, तुम्हारी मेहरबानी का शुक्र बजा लाता हूँ। निहायत सई यह थी कि आप की तरफ़ से ज़हूर में आई मैनें कलकत्ता में मुहतमिम मतबअ जाम-ए-जहाँ नुमा को लिख भेजा है और तर्क-ए-सई किया है आप भी फ़िक्र न कीजिए अगर कहीं से आप के पास आ जाए तो मुझको भेज दीजिए मेरे पास आएगा तो मैं तुम को एत्तला दे दूँगा इनायत-ए-इलाही का कौन शक़्स मुश्ताक़ न होगा उसकी पुरसिश ज़ायद में ख़िदमत गुज़ारी को हाज़िर हूँ वह जब चाहें अपना कलाम भेज दें मेरा सलाम और यह पयाम कह दीजिएगा साहब तुम ने हमारे पीर ओ मुरशिद को हम पर ख़फ़ा कर दिया भला वह ख़त न लिखें न लिखें कभी तुमको फ़रमा दें कि ग़ालिब को मेरी दुआ लिख भेजना बहर हाल मेरा सलाम-ए-नयाज़ अर्ज़ कीजिए और उनके मिज़ाज मुबारक की खैर-ओ-आफ़ियत लिखिए और यह भी लिखिए कि अगर ख़ुदा न खासता वह मुझ से नाख़ुश हैं तो नाख़ुशी कि वजह क्या है अपने चचा साहब की ख़िदमत में सलाम-ए-नयाज़ पहुँचाइएगा और मौलाना अता को सलाम-ए-शौक़ कहिएगा

– ग़ालिब

'''

== मख़दूम मुकर्रम क़ाज़ी अब्दुल जमील के नाम

जनाब-ए-आली वह गज़ल जो कहार लाया था वहाँ पहुँची जहाँ मैं जाने वाला हूँ यानी आदम-ए-मुद्दआ यह कि गुम हो गया
 	
== मख़दूम मुकर्रम क़ाज़ी अब्दुल जमील के नाम

क़िब्ला मुझे क्यों शरमिंदा किया मैं इस सना और दुआ के क़ाबिल नहीं मगर अच्छों का शेवा है बुरों को अच्छा कहना इस मदह गुस्तरी के एवज़ में आदाब बजा लाता हूँ

== मख़दूम मुकर्रम क़ाज़ी अब्दुल जमील के नाम

पीर-ओ-मुर्शिद नवाब साहब का वज़ीफ़ा ख़्वार गोया उस दर का फ़क़ीर तकियादार हूँ मसनद नशीनी कि तहनियत के वास्ते रामपुर आया मैं कहाँ और बरेली कहाँ 12 अक्टूबर को यहाँ पहुँचा बशर्त-ए-हयात आख़िर दिसम्बर तक देहली जाऊँगा नुमाइशगाह बरेली की सैर कहाँ और मैं कहाँ ख़ुद इस नुमाइशगाह की सैर से जिस को दुनिया कहते हैं दिल भर गया अब आलम-ए-बेरंगी का मुश्ताक़ हूँ ला इलाह इल्लल्लाह ला-मौजूद एलल्लाह ला-मोअस्सर फ़िलवजूद एलल्लाह

== मौलवी अज़ीज़उद्दीन के नाम

साहब कैसी साहबज़ादों की सी बातें करते हो दिल्ली को वैसा ही आबाद जानते हो जैसी आगे थी क़ासम खाँ की गली मीर ख़ैराती के फाटक से फ़तहुल्लाह बेग ख़ान के फाटक तक बे चराग है हाँ अगर आबादी है तो यह है कि ग़ुलाम हुसैन ख़ाँ की हवेली अस्पताल है और ज़ियाउद्दीन खाँ के कमरे में डाक्टर साहब रहते हैं और काले साहब के मकानों में एक और साहब आलीशान इन्गलिस्तान तशरीफ़ रखते हैं ज़ियाउद्दीन खाँ और उनके भाई मअ-कबाएल-ओ-अशाएर लोहारों हैं लाल कुएँ के मोहल्ला में ख़ाक उडती है आदमी का नाम नहीं तुम्हारे मकान में जो छोटी बेगम रहती थी उस के पास और लखमी की दुकान पर उस इश्तहार को भेजा बेगम लाहोर गयी हुई है लखमी की दुकान में कुत्ते लोटते हैं मौलवी सदरुद्दीन साहब लाहौर हैं एज़्द बख़्श तुराब अली इन लोगों से मेरी मुलाक़ात नहीं मैंने आप मोहर कर दी हुक्म-ए-अह्सनुल्लाह ख़ाँ और मियाँ ग़ुलाम नजफ़ और बहादुर बेग और नबी बख़्श ख़ाँ साकिन दरीबा उन की मोहरें हो गयीं महज़र आप के पास भेजता हूँ ख़त अज़ रूए एहतियात बेरंग भेजा है पोस्ट पेड़ ख़त अकसर तलफ़ हो जाते हैं चुनांचे काज़ी अबदुल जमील साहब का ख़त जिस का आप ने ज़िक्र लिखा है आँखे फूट जाएँ अगर मैंने देखा हो आप उन से मेरा सलाम-ए-नयाज़ कहिए और ख़त के न पहुँचने की उन को ख़बर पहुँचाइए


